-- phpMyAdmin SQL Dump
-- version 4.0.10deb1ubuntu0.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Oct 31, 2021 at 04:33 PM
-- Server version: 5.5.62-0ubuntu0.14.04.1
-- PHP Version: 5.5.9-1ubuntu4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `f32ee`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE IF NOT EXISTS `products` (
  `product_ID` int(50) NOT NULL AUTO_INCREMENT,
  `category` varchar(40) NOT NULL,
  `brand` varchar(40) NOT NULL,
  `product_model` varchar(50) NOT NULL,
  `detail` varchar(300) NOT NULL,
  `specification` varchar(800) NOT NULL,
  `price` float(6,2) NOT NULL,
  `image` varchar(60) NOT NULL,
  PRIMARY KEY (`product_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=39 ;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`product_ID`, `category`, `brand`, `product_model`, `detail`, `specification`, `price`, `image`) VALUES
(1, 'Smartphones', 'Samsung', 'Galaxy Z Flip3 5G', 'A full-sized smartphone that folds to fit small-sized pockets. This visually awesome and 4.2" folded compact design delivers the ultimate portability for every move you make.', 'Main Screen Size : 6.7" Dynamic AMOLED 2X (2640 x 1080) >\nCover Screen : 1.9" Super AMOLED (260 x 512) >\nProcessor: Qualcomm Snapdragon 888, Octa-core >\nMax. display refresh rate: 120 Hz (main) >\nCamera: 12MP Wide, 12MP Ultra wide >\nFront Camera: 10MP Front Main >\nBattery: 3,300mAh (typical) >\nMemory: 8GB >\nStorage: 256GB / 128GB >\nS Pen compatibility: No', 1398.00, 'img/product-images/1-Samsung-Flip3.png'),
(2, 'Smartphones', 'Samsung', 'Galaxy Z Fold3 5G', 'When the 7.6-inch Infinity Flex Display lights up like magic, the front camera disappears — leaving behind nothing but your YouTube video.1\nWith less bezel, no notch and an Under Display Camera, it''s the world''s first foldable phone with an uninterrupted view.', 'Main Screen Size : 7.6" Dynamic AMOLED 2X (2208 x 1768) >\nCover Screen Size : 6.2" Dynamic AMOLED 2X (832 x 2268) >\nProcessor: Qualcomm Snapdragon 888, Octa-core >\nMax. display refresh rate: 120 Hz (main, cover) >\nCamera: 12MP Wide, 12MP Ultra wide, 12MP Telephoto >\nFront Camera: 10MP Front Cover (HID), 4MP Front Main (UDC) >\nBattery: 4,400mAh (typical) >\nMemory: 12GB >\nStorage: 512GB / 256GB >\nS Pen compatibility: Yes', 2398.00, 'img/product-images/2-Samsung-Fold3.png'),
(3, 'Smartphones', 'Samsung', 'Galaxy Note20 Ultra', 'Never miss a detail with a smoother viewing experience on the Galaxy Note20 Ultra 5G''s 120Hz display. The Galaxy Note20 comes in two models, each crafted with an exquisite design and large infinity display. The Galaxy Note20 Ultra 5G has an edge display. And, with our premium Mystic color range— Mys', 'Processor: Octa Core >\nSize: 174.5mm (6.9" full rectangle) / 173.3mm (6.8" rounded corners) >\nResolution: 3088 x 1440 (Quad HD+) >\nTechnology: Dynamic AMOLED 2X >\nColour Depth: 16M >\nRear Camera - Resolution (Multiple): 108.0 MP + 12.0 MP + 12.0 MP >\nMain Camera - Auto Focus: Yes >\nMemory: 12GB >\nStorage: 256GB >\nS Pen Support: Yes (Gesture/Remote Control)', 1348.00, 'img/product-images/3-Samsung-Note20.png'),
(4, 'Smartphones', 'Apple', 'iPhone 13 Pro', 'Our biggest camera upgrade ever. All-new Pro camera system. Advanced low-light performance. Incredible detail with macro photography.', 'Capacity: 128GB, 256GB, 512GB, 1TB > \nSuper Retina XDR display with ProMotion >\n6.1?inch (diagonal) all?screen OLED display >\n2532x1170-pixel resolution at 460 ppi >\nA15 Bionic chip >\nPro 12MP camera system: Telephoto, Wide and Ultra Wide cameras >\nEnabled by TrueDepth camera for facial recognition >\nFast-charge capable: Up to 50% charge in around 30 minutes11 with 20W adapter or higher (available separately)\n', 1649.00, 'img/product-images/4-Apple-iPhone13Pro.png'),
(5, 'Smartphones', 'Apple', 'iPhone SE', 'Lots to love. Less to spend. iPhone SE packs our powerful A13 Bionic chip into our most popular size at our most affordable price. It’s just what you’ve been waiting for.', 'Capacity: 64GB, 128GB, 256GB > \nRetina HD display >\n4.7?inch (diagonal) widescreen >\n1334x750-pixel resolution at 326 ppi >\nA13 Bionic chip >\n12-megapixel Wide camera >\nFingerprint sensor built into the Home button >\nFast-charge capable: Up to 50 per cent charge in 30 minutes9 with 20W adapter or higher (sold separately)\n', 649.00, 'img/product-images/5-Apple-iPhoneSE.png'),
(6, 'Smartphones', 'HUAWEI', 'Mate 40 Pro 5G', 'See beyond the horizon and leap boldly into the future with the new HUAWEI Mate40 Pro 5G. Experience unprecedented power and speed with its Kirin 5G Chipset and take exceptional videos with its Ultra Vision Cine Camera.', 'Dimensions: 162.9 x 75.5 x 9.1 mm >\nWeight: 212g >\nCamera: 4K, 60fps >\nBattery: 4400mAh >\nStandby Time: 539 hrs >\nInternal Memory: 256GB >\nCard Slot: Up to 256GB >\nRAM: 8GB >\nSpeed: LTE 1.6 Gbps + NR 2.3 Gbps >\nLTE Network: LTE 700 / 800 / 850 / 900 / 1800 / 1900 / 1900(TD) / 2300(TD) / 2500(TD)/ 2600(FDD/TD) >\nVoLTE Supported: Yes\n', 1298.00, 'img/product-images/6-Huawei-Mate40.png'),
(7, 'Smartphones', 'HUAWEI', 'P40 Pro', 'Speak for yourself with the Ultra Vision Leica Quad Camera by capturing photos and videos anytime and anywhere you want. Revolutionize your experience of speed and power with the cutting-edge Kirin 990 5G Chipset. The innovative design upgrades your visual entertainment and ergonomic comfort. Explor', 'Dimensions: 158.2 x 72.6 x 8.95 mm >\nWeight: 209g >\nCPU: Octa-core, 2 x Cortex-A76 Based 2.86 GHz + 2 x Cortex-A76 Based 2.36 GHz + 4 x Cortex-A55 1.95 GHz >\nGPU: Mali-G76 >\nCPU process: 7nm+ EUV >\nNPU: Dual Big Core + Tiny Core NPUs (Neural-network Processing Unit) >\nCamera: 50 MP Ultra Vision Camera >\nBattery: 4200mAh >\nStandby Time: 539 hrs >\nMemory: 8 GB RAM + 256 GB ROM \n\n', 1448.00, 'img/product-images/7-Huawei-P40.png'),
(8, 'Smartphones', 'Oppo', 'Reno6 Pro 5G', 'Take the perfect portrait with our industry-leading Bokeh Flare Portrait Video, powered by AI algorithms which run thousands of computations a second, to turn background lights into dreamy spheres full of rich color, also our exclusive OPPO Reno Glow shine has been created with over 20 patents appli', 'Display Size: 6.53‘’ FHD+ Screen >\r\nFront Camera: 32MP >\r\nRear Camera: 64MP AI Triple Camera / 8MP Ultra Wide-angle Camera / 2MP Macro & Mono Camera >\r\nBattery capacity?4500 mAh Battery >\r\nSIM Card Type: Dual Nano Sim, Non-Expandable SD Card MediaTek Dimensity 1200 >\r\nFingerprint Sensor & AI Face Unlock >\r\nRefresh Rate: 90 Hz >\r\nRAM?12GB RAM + 256GB ROM >\r\nColorOS 11.3 based on Android 11', 899.00, 'img/product-images/8-Oppo-Reno6.png'),
(9, 'Smartphones', 'Oppo', 'A16', 'HD+ Eye-care Display.\nProtect your eyes with our HD+ Eye-care display whereby the screen doesn’t send harmful blue light to viewers which can strongly damage eyesight', 'Display Size: 6.52‘’ HD+ Screen >\nFront Camera: 8MP >\nRear Camera: 13MP AI Triple Camera >\nBattery capacity?5000 mAh Battery >\nSIM Card Type: Dual Nano Sim, Triple Slot, Expandable up to 256GB >\nMediaTek Helio G35 >\nFingerprint Sensor & AI Face Unlock >\nRAM?4GB RAM + 64GB ROM >\nColorOS 11.1 Based on Android 11', 229.00, 'img/product-images/9-Oppo-A16.png'),
(10, 'Laptops', 'Apple', 'MacBook Air', 'Available in silver, space grey, and gold, the latest MacBook Air features twice the performance and double the storage. It comes with a stunning Retina display with True Tone technology, Touch ID, a backlit Magic Keyboard, and a Force Touch trackpad—all housed in a thin and light iconic wedge desig', 'Stunning 13.3-inch Retina display with True Tone technology >\nBacklit Magic Keyboard and Touch ID >\nTenth-generation Intel Core i3 or i5 processor >\nIntel Iris Plus Graphics >\nFast SSD storage >\n8GB of memory >\nStereo speakers with wider stereo sound >\nTwo Thunderbolt 3 (USB-C) ports >\nUp to 11 hours of battery life >\nForce Touch trackpad >\n802.11ac Wi-Fi >\nAvailable in gold, space grey, and silver >\nThe latest version of macOS >', 1249.00, 'img/product-images/10-Apple-MacbookAir.png'),
(11, 'Laptops', 'Apple', 'Macbook Pro', 'Expand your view of everything on MacBook Pro with an immersive 16-inch Retina display that delivers spectacular bright whites, deeper blacks, and up to 500 nits of brightness. Harness the power of 6- or 8-core processors, along with AMD Radeon Pro 5000M series graphics with up to 8GB of High Bandwi', 'Ninth-generation 6-core Intel Core i7 or 8-core Intel Core i9 processor >\nBrilliant 16-inch Retina display with True Tone technology1 >\nTouch Bar and Touch ID >\nAMD Radeon Pro 5300M or 5500M graphics with GDDR6 memory >\nUltrafast SSD >\nIntel UHD Graphics 630 >\nSix-speaker system with force-cancelling woofers >\nFour Thunderbolt 3 (USB-C) ports >\nUp to 11 hours of battery life >\n802.11ac Wi-Fi >\nBacklit Magic Keyboard >\nForce Touch trackpad >\nAvailable in space grey and silver >\nThe latest version of macOS ', 3499.00, 'img/product-images/11-Apple-MacbookPro.png'),
(12, 'Laptops', 'HP', 'Spectre x360 Convertible 14', 'A 2-in-1 PC that can read the room.\nThe HP Spectre x360 adapts to the way you use it for just the right display and power settings.', 'Operating system: Windows 10 Home 64 >\nProcessor: Intel® Core™ i7-1165G7 (up to 4.7 GHz with Intel® Turbo Boost Technology, 12 MB L3 cache, 4 cores) >\nProcessor family: Intel® Evo™ platform feat 11th Gen Intel® Core™ i7 processor with Intel® Iris® Xe graphics >\nChipset: Intel® Integrated SoC >\nForm factor: Convertible >\nMemory: 16 GB LPDDR4-3200 SDRAM (onboard) >\nMemory Note: Transfer rates up to 3200 MT/s. >\nWarranty: 2 years Parts, Labour, 3 working days onsite response + 2 Year Next Business Day Accidental Damage Protection.', 2699.00, 'img/product-images/12-HP-Spectre.png'),
(13, 'Laptops', 'HP', 'Laptop 14s', 'Affordable laptop with reliable performance to keep up with your daily tasks.', 'Operating system: Windows 10 Home 64 >\nProcessor: Intel® Core™ i5-1135G7 (up to 4.2 GHz with Intel® Turbo Boost Technology, 8 MB L3 cache, 4 cores) >\nProcessor family: 11th Generation Intel® Core™ i5 processor >\nChipset: Intel® Integrated SoC >\nForm factor: Standard laptop >\nMemory: 8 GB DDR4-2666 SDRAM (2 x 4 GB) >\nMemory Note: Transfer rates up to 2666 MT/s. >\nWarranty: 2 years Parts, Labour, 3 working days onsite response', 929.00, 'img/product-images/13-HP-Laptop14.png'),
(14, 'Laptops', 'HP', 'VICTUS 16', 'For your gaming and productivity needs. Get ready to work and play with the latest processor and graphics, and a FHD, fast display.', 'Operating system: Windows 10 Home 64 >\nProcessor: Intel® Core™ i7-11800H (up to 4.6 GHz with Intel® Turbo Boost Technology, 24 MB L3 cache, 8 cores, 16 threads)  >\nProcessor family: 11th Generation Intel® Core™ i7 processor >\nChipset: Intel® HM570 >\nForm factor: Standard laptop >\nMemory: 16 GB DDR4-3200 MHz RAM (2 x 8 GB) >\nMemory Note: Transfer rates up to 3200 MT/s. >\nWarranty: 2 years Onsite Warranty & 2 years Accident Damage Protection', 1999.00, 'img/product-images/14-HP-VICTUS16.png'),
(15, 'Laptops', 'Lenovo', 'ThinkPad X1 Carbon Gen 9', 'Power & portability in a premium package.\nThe 14" ThinkPad X1 Carbon Gen 9 laptop rolls out a host of new features that add convenience, improve technology, and enrich your experience—all while retaining an ultrathin and ultralight chassis. You’ll discover an impressive 16:10 display, a wider TouchP', 'Processor: Up to 11th Gen Intel® Core™ i7 vPro® >\nOperating System: Up to Windows 11 Pro >\nDisplay: 16 GB Soldered LPDDR4x 4266MHz >\nMemory: Up to 32GB LPDDR4x >\nBattery: Up to 16 hours* 57Whr (MM18) >\nStorage: Up to 2TB PCIe SSD Gen 4 Performance >\nGraphics: Intel® Iris® Xe >\nAudio: Dolby Atmos® Speaker System; 4 x 360-degree far-field microphones; Dolby Voice® professional conferencing solution >\nCamera: 720p HD with webcam privacy shutter >\nOptional: Hybrid infrared (IR) / 720p HD with webcam privacy shutter', 3273.04, 'img/product-images/15-Lenovo-Carbon.png'),
(16, 'Laptops', 'Lenovo', 'ThinkPad X1 Yoga Gen 6', 'Premium experience redefined.\nMeet the 6th generation of the ThinkPad X1 Yoga, a 14" 2-in-1 touchscreen laptop that’s been reimagined to enhance your experience. You’ll still find the details you’ve enjoyed on our premium X1 Yoga, and you’ll discover an impressive 16:10 display, a wider TouchPad, a ', 'Processor : 11th Generation Intel® Core™ i5-1135G7 Processor (4 Cores / 8 Threads, 2.40 GHz, up to 4.20 GHz with Turbo Boost, 8 MB Cache) >\nOperating System: Windows 10 Pro 64 >\nDisplay Type: 14.0" WUXGA (1920x1200) IPS 400nits Anti-glare, Touch >\nMemory: 16 GB Soldered LPDDR4x 4266MHz >\nStorage: 512 GB M.2 2280 SSD >\nWarranty: 3 Year Premier Support >\nGraphics: Intel® Iris® Xe Graphics >\nBattery: 4 Cell, 57Wh >\nCamera: 720p + IR with PrivacyShutter >\nPen: Lenovo Integrated Pen >\nFingerprint Reader >\nWireless: Intel Wi-Fi 6 AX201 11AX (2x2) & Bluetooth® 5.2 >', 3212.24, 'img/product-images/16-Lenovo-Yoga.png'),
(17, 'Laptops', 'Dell', 'Inspiron 14 Laptop', 'Featuring AMD Ryzen™ 5000 Series Mobile Processors with Radeon™ Graphics and a redesigned thermal system unleashes the power of your device while also preserving its thin design.', 'Processor: AMD Ryzen™ 5 5500U 6-core/12-thread Mobile Processor with Radeon™ Graphics >\nOperating System: Windows 10 Home (64bit) English >\nVideo Card: AMD Radeon™ Graphics with shared graphics memory >\nDisplay: 14.0-inch FHD (1920 x 1080) Anti-glare LED Backlight Non-Touch Narrow Border WVA Display >\nMemory: 8GB DDR4 3200MHz >\nHard Drive: 512GB M.2 PCIe NVMe Solid State Drive >\nSlots: 1 microSD-card slot >\nCamera: 720p at 30 fps HD camera, dual-array microphones >\nAudio and Speakers: 2 W stereo speaker >\nWireless: Intel® Wi-Fi 6 AX200 2x2 (Gig+) + Bluetooth 5 >\nPrimary Battery: 4-Cell Battery, 54WHr (Integrated)', 948.99, 'img/product-images/17-Dell-Inspiron.png'),
(18, 'Laptops', 'Dell', 'Alienware m17 R4 Gaming Laptop', 'Alienware''s thin 17-inch laptop featuring options that include maximum performance NVIDIA® GeForce RTX™ 30-series graphics. Features advanced Alienware Cryo-Tech and Hyper-Efficient Voltage Regulation for your gaming needs.', 'PROCESSOR: 10th Generation Intel® Core™ i7-10870H (8-Core, 16MB Cache, up to 5.0GHz Max Turbo Frequency) >\nOPERATING SYSTEM: Windows 11 Home; Alienware recommended >\nVIDEO CARD: NVIDIA® GeForce RTX™ 3070 8GB GDDR6 >\nMEMORY: 16GB DDR4 2933MHz >\nKEYBOARD: Alienware mSeries per-key AlienFX Cherry RGB keyboard - US/International >\nWIRELESS: Killer™ Wi-Fi 6 AX1650 802.11ax 2x2 Wireless LAN and Bluetooth 5.1 >\nPOWER OPTIONS: Power Cord (UK) >\nPRIMARY BATTERY: 6-Cell Battery, 86WHr (Integrated) >\nAC ADAPTER: 240W Power Adapter', 2399.01, 'img/product-images/18-Dell-m17.png'),
(19, 'Desktops', 'Apple', '24'''' iMac', 'Apple M1 chip with 8-core CPU with 4 performance cores and 4 efficiency cores, 8-core GPU and 16-core Neural Engine', '8GB unified memory >\n256GB SSD storage >\nTwo Thunderbolt / USB 4 ports >\nTwo USB 3 ports >\nGigabit Ethernet >\nMagic Mouse >\nMagic Keyboard with Touch ID - US English', 2149.00, 'img/product-images/19-Apple-iMac.png'),
(20, 'Desktops', 'Dell', 'Alienware Aurora Gaming Desktop', 'Extensive cooling with integrated vapor chambers – our largest diameter heat pipe design to date – designed for exceptional gaming performance. With new 80 PLUS Gold rated 1000W power supply, it delivers incredible overall performance.', '11th Gen Intel® Core™ i5 11400F (6-Core, 12MB Cache, 2.6Ghz to 4.4GHz) >\nWindows 11 Home, English >\nNVIDIA® GeForce RTX™ 3060 12GB GDDR6 >\n16GB, 2x8GB, DDR4, 3200MHz, XMP >\n512GB M.2 PCIe NVMe SSD >\nLunar Light chassis with High-Performance CPU Liquid Cooling and 1000W Power Supply', 2499.00, 'img/product-images/20-Dell-Aurora.png'),
(21, 'Desktops', 'Dell', 'XPS Desktop', 'Designed for Easy to access & upgrade. Three PCle slots let you add in sound cards, graphics cards, and more as you customize your machine.', '10th Gen Intel® Core™ i7-10700 processor(8-Core, 16M Cache, 2.9GHz to 4.8GHz) >\nWindows 11 Home, English >\nNVIDIA® GeForce® RTX 3060 Ti™ 8GB GDDR6 >\n16GB, 8Gx2, DDR4, 2933MHz >\n512GB PCIe M.2 SSD +1TB SATA 7200 RPM HDD', 2099.01, 'img/product-images/21-Dell-XPS.png'),
(22, 'Desktops', 'Dell', 'Inspiron Compact Desktop', 'All in a space-saving design built with 10th or 11th Gen Intel® Core™ processors you can expect fast, reliable performance and an exceptional PC experience', '10th Gen Intel® Core™ i3-10105 processor >\nWindows 11 Home >\nIntel® UHD Graphics 630 with shared graphics memory >\n8GB, 8Gx1, DDR4, 2666MHz >\n256GB M.2 PCIe NVMe Solid State Drive + 1TB 7200 rpm 3.5" SATA Hard Drive >', 714.00, 'img/product-images/22-Dell-Inspiron.png'),
(23, 'Desktops', 'HP', 'HP Pavilion Desktop TP01-2155m PC', 'Real-life action demands serious performance and tested durability. The HP Pavilion Desktop PC brings high performance and reliability from a trusted brand that protects what matters to you most.', 'Windows 11 Home >\nAMD Ryzen™ 3 processor >\nAMD Radeon™ Graphics >\n8 GB memory; 1 TB HDD storage; 256 GB SSD storage >\nDVD-Writer >', 549.99, 'img/product-images/23-HP-Pavilion2155m.png'),
(24, 'Desktops', 'HP', 'HP Pavilion Desktop TP01-2165z PC', 'Real-life action demands serious performance and tested durability. The HP Pavilion Desktop PC brings high performance and reliability from a trusted brand that protects what matters to you most.', 'Windows 11 Home >\nAMD Ryzen™ 5 processor >\nAMD Radeon™ Graphics >\n16 GB memory; 2 TB HDD storage; 256 GB SSD storage >\nDVD-Writer', 699.99, 'img/product-images/24-HP-Pavilion2165z.png'),
(25, 'Desktops', 'HP', 'OMEN 25L Gaming Desktop PC GT12-1340m', 'Behold your new best friend, your partner in play, your compadre in competition, the OMEN 25L Desktop PC packs a staggeringly fast Intel processor with a dazzling NVIDIA® graphics card, so you can play on your level and look good while you''re doing it. Just open the box and close in on the competiti', 'Windows 10 Home 64 >\nAMD Ryzen™ 5 processor >\nAMD Radeon™ RX 5500 Graphics >\n8 GB Memory; 256 SSD storage >', 1049.99, 'img/product-images/25-HP-Omen25L.png'),
(26, 'Desktops', 'HP', 'HP Pavilion Gaming Desktop TG01-2285t Bundle PC', 'Get ready to game on your terms. This powerful rig is built to keep up with the games of today and tomorrow. Beneath its compact and sleek exterior, you will find all the performance you need to play with confidence and room to expand and upgrade.', 'Windows 10 Home 64 >\n11th Generation Intel® Core™ i7 processor >\nNVIDIA® GeForce RTX™ 3060 (12 GB GDDR6 dedicated) >\n16 GB memory; 2 TB HDD storage; 256 GB SSD storage >', 1349.99, 'img/product-images/26-HP-PavilionGaming.png'),
(27, 'Desktops', 'HP', 'OMEN 30L Desktop GT13-0255st', 'It’s gaming love at first sight. The OMEN 30L Desktop PC has got the looks and can back it up. With a power processor and graphics, you can play day one. And with being easy to upgrade and OMEN Gaming Hub, it’s crafted for the long term.', 'Windows 10 Home 64 >\n10th Gen Intel® Core™ i5 processor >\nNVIDIA® GeForce RTX™ 2060 Super >\n8 GB Memory; 256 SSD storage >', 1499.99, 'img/product-images/27-HP-Omen30L.png'),
(28, 'Earbuds', 'Samsung', 'Galaxy Buds2', 'Get lost in what you love. Galaxy Buds2 opens a new world of audio experience with well-balanced sound, unmatched comfort fit, ANC, and seamless connectivity to your phone and watch. Easier controls and better feedback keep you immersed when working out, gaming, or jamming to your beats.', 'Sound quality that enriches every audio journey. >\nTwo microphones help with blocking unwanted sound. >\nThe lightest earbuds we''ve ever made. >', 248.00, 'img/product-images/28-Samsung-GalaxyBuds.png'),
(29, 'Earbuds', 'Samsung', 'Galaxy Buds+ BTS Edition', 'Our first ever wireless earbuds with a 2-way\nspeaker delivering sound by AKG.\nEnjoy a premium listening experience with crystal clear calls\nand long-lasting battery power.', 'Up to 22 hours battery life >\n2-way dynamic speaker >\n2 outer mics and 1 inner mic ', 389.00, 'img/product-images/29-Samsung-BTSedition.png'),
(30, 'Earbuds', 'Samsung', 'Galaxy Buds Live', 'Earbuds designed to tune in to every moment. With an iconic shape and ergonomic design, the adaptive fit lets in desired sounds from your natural surroundings, and a dynamic speaker system optimised for a better experience. This is sound made just for your ears.', 'Ergonomic design and fit >\nOpen type Active Noise Cancellation >\nRich, immersive sound quality >', 288.00, 'img/product-images/30-Samsung-GalaxyBudsLive.png'),
(31, 'Earbuds', 'Apple', 'AirPods Pro', 'AirPods Pro have been designed to deliver Active Noise Cancellation for immersive sound, Transparency mode so you can hear your surroundings and a customisable fit for all-day comfort. Just like AirPods, AirPods Pro connect magically to your Apple devices. And they’re ready to use straight out of th', 'Designed by Apple>\nActive Noise Cancellation >\nMore customisable fit and seal >\nTransparency mode >\nAmazing sound quality with Adaptive EQ >\nSweat and water resistant (IPX4)³ >\nAutomatically on, automatically connected  >\nEasy setup for all your Apple devices >\nCase can be charged either wirelessly using a MagSafe charger or Qi-certified charger, or with the Lightning connector ', 379.00, 'img/product-images/31-Apple-AirpodsPro.png'),
(32, 'Earbuds', 'Apple', 'AirPods (3rd generation)', 'AirPods are lightweight and offer a contoured design. They sit at just the right angle for comfort and to better direct audio to your ear. The stem is 33 per cent shorter than AirPods (2nd generation) and includes a force sensor to easily control music and calls.', 'Designed by Apple >\nSpatial audio with dynamic head tracking for an immersive, three-dimensional listening experience¹ >\nAmazing sound quality with Adaptive EQ >\nContoured design >\nForce sensor control >\nSweat and water resistant (IPX4)³ >\nEasy setup for all your Apple devices >\nCase can be charged either wirelessly using a MagSafe charger or Qi-certified charger, or with the Lightning connector', 269.00, 'img/product-images/32-Apple-Airpods3rdGen.png'),
(33, 'Earbuds', 'Apple', 'AirPods (2nd generation)', 'AirPods deliver the wireless headphone experience, reimagined. Just pull them out of the charging case and they’re ready to use with your iPhone, Apple Watch, iPad or Mac.', 'Designed by Apple >\nAutomatically on, automatically connected >\nEasy setup for all your Apple devices? >\nQuick access to Siri by saying “Hey Siri” or setting up double-tap >\nDouble-tap to play or skip forward >\nCharges quickly in the case >\nCase can be charged with a Lightning connector >\nRich, high-quality audio and voice\n\nSeamless switching between devices', 199.00, 'img/product-images/33-Apple-Airpods2ndGen.png'),
(34, 'Earbuds', 'Sony', 'WF-1000XM4 Wireless Noise Cancelling Headphones', 'An exceptional listening experience that’s tailored just for you. The WF-1000XM4 truly wireless headphones take industry-leading noise cancelling and audio quality to the next level. Made to fit every ear, they offer a personalised experience that adjusts to every situation.', 'Evolved Digital Noise Cancelling with Integrated Processor V1 >\nSound quality with High-Resolution Audio Wireless >\nSmart listening and clear call quality >\nErgonomic surface design for stable fit >\nWater resistant and long battery life for everyday use', 379.00, 'img/product-images/34-Sony-WF1000XM4.png'),
(35, 'Watches', 'Apple', 'Starlight Aluminium Case with Braided Solo Loop', 'The aluminium case is lightweight and made from 100 per cent recycled aerospace-grade alloy.\nThe Braided Solo Loop is made from recycled yarn interwoven with silicone threads for an ultra-comfortable, stretchable design with no clasps or buckles.', 'Always-On Retina LTPO OLED display, 1,000 nits >\nIon-X glass display on aluminium cases > \nSapphire crystal display on stainless steel and titanium cases >\nGPS and GPS + Cellular models >\nS7 SiP with 64-bit dual-core processor >\nW3 wireless chip ', 679.00, 'img/product-images/35-Apple-Starlight.png'),
(36, 'Watches', 'Apple', 'Midnight Aluminium Case with Sport Band', 'The aluminium case is lightweight and made from 100 per cent recycled aerospace-grade alloy.\nThe Sport Band is made from a durable yet surprisingly soft high-performance fluoroelastomer, with an innovative pin-and-tuck closure.\n\n', 'Always-On Retina LTPO OLED display, 1,000 nits >\nIon-X glass display on aluminium cases > \nSapphire crystal display on stainless steel and titanium cases >\nGPS and GPS + Cellular models >\nS7 SiP with 64-bit dual-core processor >\nW3 wireless chip ', 599.00, 'img/product-images/36-Apple-Midnight.png'),
(37, 'Watches', 'HUAWEI', 'Huawei Watch 3 Active LTE', 'Let what you wear on your wrist fit seamlessly into your life. The circular finish and rounded screen offer a classic look and flowing feel, while the stunning 1.43-inch AMOLED display pushes smartWatch design into a bright future, right before your eyes.', 'AMOLED color screen >\nSupport full-screen touch operations, including swiping, tapping, and pressing and holding >\nOptical heart rate sensor >\nAmbient light sensor >\nWireless charging >', 548.00, 'img/product-images/37-Huawei-Watch3.png'),
(38, 'Watches', 'HUAWEI', 'Huawei Watch GT 2 46mm Smartwatch', 'HUAWEI WATCH GT series is always exploring the limits of smart watch battery life. With HUAWEI''s self-developed wearable chip Kirin A1, the dual-chip design and intelligent power saving technology, it serves you day and night for up to 2 weeks', '1.39 inch AMOLED 454 x 454 HD >\nTouchscreen supports slide and touch gestures >\nOptical heart rate sensor >\r\nAmbient light sensor >\nMagnetic charging thimble', 268.00, 'img/product-images/38-Huawei-WatchGT2.png');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
